---
title: "3D Maps"
author: "Fitrah Ramadhan"
date: "2023-12-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import Libraries

```{r packages, include=FALSE}

#libraries we need
libs <- c('tidyverse','sf','janitor','classInt','tmaptools','spdep','rayshader','here','tmap', 'ggplot2', 'extrafont')

#install missing libraries
installed_libs <- libs %in% rownames(installed.packages())
if (any(installed_libs == F)) {
  install.packages(libs[!installed_libs])
}

#load packages
invisible(lapply(libs, library, character.only = T))

#check version
checkVersion <- function(packages) {
  print(paste(packages," : ", packageVersion(packages)))
}

invisible(lapply(libs, checkVersion))
```

### Get Hexagonal Grid of London

```{r}

london <- st_read('https://www.dropbox.com/scl/fi/qmuuncr9luoguae5wa6ho/neighbourhoods.geojson?rlkey=rflewdp5df2am8ydpstessz20&dl=1') %>% st_transform(27700)
```

```{r}

london_hex <- st_make_grid(london,
                           cellsize = 1000,
                           what = 'polygon',
                           square = F) %>%
  st_intersection(london) %>%
  st_sf() %>%
  mutate(id = row_number()) %>% 
  filter(st_geometry_type(.) %in% c("POLYGON", "MULTIPOLYGON")) %>%
  st_cast("MULTIPOLYGON")
```

### Airbnb Data

```{r}

airbnb <- readr::read_csv('https://www.dropbox.com/scl/fi/zrr90ju1ir8h56hbf079n/listings.csv?rlkey=673iaen39g7qdqopr47nvc9qy&dl=1') 

airbnb <- st_as_sf(airbnb, coords=c('longitude', 'latitude'), crs=4326) %>% st_transform(27700)

airbnb <- airbnb[london_hex,]
```

```{r}

tmap_mode('plot')

tm_shape(london_hex) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(airbnb) +
  tm_dots(col = 'blue')
```

```{r}

airbnb <- airbnb %>%
  dplyr::select(., price) %>%
  dplyr::mutate(price = sub("\\$","", price)) %>%
  dplyr::mutate(price = as.numeric(price))

```

```{r}

mean_price_hex <- airbnb %>% st_join(., london_hex)
mean_price_hex <- mean_price_hex %>%
  dplyr::group_by(id) %>%
  dplyr::summarize(mean = mean(price, na.rm=TRUE))
```

```{r}

london_hex <- london_hex %>%
  st_join(., mean_price_hex, by='id') 

london_hex <- london_hex %>% 
  clean_names %>%
  dplyr::select(id = id_x, mean) %>%
  dplyr::mutate(mean = ifelse(is.na(mean), 0, mean))

```

### Visualization

```{r}

vmin <- min(london_hex$mean, na.rm=T)
vmax <- max(london_hex$mean, na.rm=T)

brk <- round(classIntervals(london_hex$mean, 
                            n = 6, 
                            style = 'fisher')$brks, 1) %>%
  head(-1) %>%
  tail(-1) %>%
  append(vmax)

breaks <- c(vmin, brk)
all_breaks <- list(vmin, vmax, breaks)

cols = rev(c("#8F0909", "#FF1C1C", "#FF5446", "#FF8773", "#FFB6A6", "white"))
newcol <- colorRampPalette(cols)
ncols <- 6
cols2 <- newcol(ncols)
```

```{r}


p <- ggplot(london_hex) +
  geom_sf(aes(fill = mean), color = NA, size=0) +
  scale_fill_gradientn(name="In USD ($)",
                       colours=cols2,
                       breaks=breaks,
                       labels=round(breaks, 1),
                       limits=c(vmin, vmax))+   
  guides(fill=guide_legend(direction = "horizontal",
                           keyheight = unit(2.5, units = "mm"),
                           keywidth = unit(2.55, units = "mm"),
                           title.position = 'top',
                           title.hjust = .5,
                           label.hjust = .5,
                           nrow = 7,
                           byrow = T,
                           reverse = F,
                           label.position = "left")) +
  coord_sf(crs = 4326)+
  theme_minimal() +
  theme(text = element_text(family = "Arial", color = "#22211d"),
        axis.line = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = c(0.9, .1),
        legend.text = element_text(size=6, color="white"),
        legend.title = element_text(size=8, color="white"),
        panel.grid.major = element_line(color = "grey60", size = 0.2),
        panel.grid.minor = element_blank(),
        plot.title = element_text(size=12, color="white", hjust=1, face="bold", vjust=-1),
        plot.caption = element_text(size=6, color="white", hjust=.15, vjust=20),
        plot.subtitle = element_text(size=12, color="white", hjust=1),
        plot.margin = unit(c(t=0, r=0, b=0, l=0),"lines"),
        plot.background = element_rect(fill = "grey60", color = NA), 
        panel.background = element_rect(fill = "grey60", color = NA), 
        legend.background = element_rect(fill = "grey60", color = NA),
        panel.border = element_blank())+
  labs(x = "", 
       y = NULL, 
       title = "Mean Rent Price per Night of Airbnb in London 2019", 
       subtitle = expression(paste("per 1 ", km^{2}, "of land area")), 
       caption = "Inspiration from Milos Popovic (2022)\n Data: insideairbnb.com")
```

```{r}

plot(p)
```

```{r}

plot_gg(p,
  multicore = T,
  width=5,
  height=5,
  scale=150,
  shadow_intensity = .75,
  sunangle = 360,
  offset_edges=T,
  windowsize=c(1400,866),
  zoom = .4, 
  phi = 30, 
  theta = -30)

render_snapshot("airbnb_meanprice_2019.png", clear=T)
```
